import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {user.isSignedIn ? <SignOutButton /> : <SignInButton />}
        <div>
          {data?.map((item) => (
            <div key={item.id}>{item.content}</div>
          ))}
        </div>
      </main>
    </>
  );
}
